spring.datasource.url=jdbc:mysql://localhost:3306/spendix_db
spring.datasource.username=root
spring.datasource.password=groot

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

jwt.secret=ThisIsAVerySecretKeyForSpendixApp12345678
jwt.expiration=86400000